---
name: csit-trex-perf-ndrpdr-weekly

# yamllint disable-line rule:truthy
on:
  # Runs periodically
  #schedule:
  #  - cron:  "0 0 * * 6"
  workflow_dispatch:

jobs:
  csit-trex-perf-ndrpdr-weekly-master-2n-icx:
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:os=ubuntu2404
    timeout-minutes: 3600

    env:
      JOB_NAME: ${{ github.job }}
      BUILD_TAG: ${{ github.job }}-${{ github.run_id }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - name: Run CSIT Bootstrap
        # yamllint disable-line rule:line-length
        uses: fdio/csit/.github/actions/csit-bootstrap@a372372ca8f89676c55631f8650468dfab86cc2a
        with:
          bootstrap_script: bootstrap_verify_perf.sh
          with_oper: true

      - name: AWS S3 Publish Logs
        if: ${{ always() }}
        # yamllint disable-line rule:line-length
        uses: pmikus/.github/.github/actions/aws-s3-publish-logs@d2c8485d9e23e6c439c8eebae3f8101fb48fcb86
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          s3_bucket: ${{ vars.S3_BUCKET }}
          s3_path: ${{ github.job }}/${{ github.run_id }}