---
name: csit-report-dispatch

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      job_type:
        description: "The type of job: iterative or coverage."
        required: true
        type: choice
        options:
          - iterative
          - coverage
        default: iterative
      node:
        description: Performance testbed node.
        required: true
        type: choice
        options:
          - 2n-emr
          - 2n-grc
          - 2n-icx
          - 2n-spr
          - 2n-zn2
          - 3n-alt
          - 3n-emr
          - 3n-icx
          - 3n-icxd
          - 3n-oct
          - 3n-snr
          - 3na-spr
          - 3nb-spr
        default: 2n-emr
      branch:
        description: Branch or patch.
        required: true
        type: string
        default: rls2510
      suite_gen_params:
        description: Parameters for the suite generator.
        required: true
        type: string

jobs:
  dispatch:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          set -ex
          case "${{ inputs.node }}" in
            "2n-emr")
                echo "matrix={\"include\":[{\"node\":\"2n-emr\",\"executor_arch\":\"x86_64\",\"os\":\"ubuntu2404\"}]}" >> $GITHUB_OUTPUT
            ;;
          esac

  csit-perf-report:
    needs: dispatch
    # yamllint disable-line rule:line-length
    name: csit-dpdk-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.branch }}-${{ matrix.node }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}
    timeout-minutes: 3600

    strategy:
      matrix: ${{ fromJSON(needs.dispatch.outputs.matrix) }}

    env:
      JOB_NAME: csit-dpdk-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.branch }}-${{ matrix.node }}
      GERRIT_BRANCH: ${{ github.event.inputs.branch }}

    steps:
      - run: echo "${{ env.JOB_NAME }}"

      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@8930b575136625c5c8a47752192f9cd90202bea3

      #- name: Run Performance Bootstrap
      #  uses: fdio/csit/.github/actions/csit-bootstrap@3835964003f751ea545d7926f46fade5e9e5da13
      #  with:
      #    bootstrap_script: bootstrap_verify_perf.sh
      #    with_oper: false

      #- name: Archive Logs
      #  if: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ${{ env.JOB_NAME }}-${{ github.run_number }}
      #    path: archives/
      #    if-no-files-found: ignore

      #- name: AWS S3 Publish Logs
      #  if: always()
      #  uses: pmikus/.github/.github/actions/aws-s3-publish-logs@8930b575136625c5c8a47752192f9cd90202bea3
      #  with:
      #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws_region: ${{ vars.AWS_REGION }}
      #    s3_bucket: ${{ vars.S3_BUCKET }}