---
name: csit-dpdk-perf-report

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      job_type:
        description: "The type of job: iterative or coverage."
        required: true
        type: string
        default: iterative
      node:
        description: Performance testbed node.
        required: true
        type: string
        default: 2n-emr
      arch:
        description: Performance testbed architecture.
        required: true
        type: string
      os:
        description: Performance testbed operating system.
        required: true
        type: string
      branch:
        description: Branch or patch.
        required: true
        type: string
        default: rls2510
      suite_gen_params:
        description: Parameters for the suite generator.
        required: true
        type: string

jobs:
  csit-dpdk-perf-report:
    # yamllint disable-line rule:line-length
    name: csit-dpdk-perf-report-${{ github.event.inputs.job_type }}-${{ github.event.inputs.node_arch }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ inputs.arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ inputs.os }}

    env:
      # yamllint disable-line rule:line-length
      JOB_NAME: csit-dpdk-perf-report-${{ github.event.inputs.JOB_TYPE }}-${{ matrix.node }}
      GERRIT_BRANCH: ${{ github.event.inputs.branch }}
      GERRIT_EVENT_COMMENT_TEXT: ${{ github.event.inputs.SUITE_GEN_PARAMS }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@8930b575136625c5c8a47752192f9cd90202bea3

      #- name: Run Performance Bootstrap
      #  uses: fdio/csit/.github/actions/csit-bootstrap@3835964003f751ea545d7926f46fade5e9e5da13
      #  with:
      #    bootstrap_script: bootstrap_verify_perf.sh
      #    with_oper: false

      #- name: Archive Logs
      #  if: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ${{ env.JOB_NAME }}-${{ github.run_number }}
      #    path: archives/
      #    if-no-files-found: ignore

      #- name: AWS S3 Publish Logs
      #  if: always()
      #  uses: pmikus/.github/.github/actions/aws-s3-publish-logs@8930b575136625c5c8a47752192f9cd90202bea3
      #  with:
      #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws_region: ${{ vars.AWS_REGION }}
      #    s3_bucket: ${{ vars.S3_BUCKET }}