---
name: csit-trex-perf-ndrpdr-weekly

# yamllint disable-line rule:truthy
on:
  # Runs periodically
  #schedule:
  #  - cron:  "0 0 * * 6"
  workflow_dispatch:

jobs:
  csit-trex-perf-ndrpdr-weekly-master-2n-icx:
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=dev
      - fdio:os=ubuntu2404
    timeout-minutes: 3600

    env:
      JOB_NAME: ${{ github.job }}
      BUILD_TAG: ${{ github.job }}-${{ github.run_id }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0
